relaod core so changes from config update take effect

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -161,11 +161,14 @@ fi
 
 /etc/init.d/solr restart
 
-###### TRY TO RELOAD THE CORE
+###### Create cores if fresh install - otherwise update and reload cores.
 if [ -z "$FRESH_SEARCH_CORE_INSTALL" ]; then
 	if ! (${SOLR_ROOT}/server/scripts/cloud-scripts/zkcli.sh -cmd upconfig -z localhost:2181 -confname ${SEARCH_CORE_NAME} -confdir ${SEARCH_CONFIGS_DIR}conf/ >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 		log "UPDATE of $SEARCH_CORE_NAME config failed"
 	fi
+	if ! (curl "http://localhost:8983/solr/admin/cores?action=RELOAD&core=$SEARCH_CORE_NAME" >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "RELOAD of $SEARCH_CORE_NAME failed"
+	fi	
 else
 	if ! (${SOLR_ROOT}/bin/solr create -c ${SEARCH_CORE_NAME} -d ${SEARCH_CONFIGS_DIR} -rf 3 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 			log "ERROR creating solr core $SEARCH_CORE_NAME failed"
@@ -175,6 +178,9 @@ fi
 if [ -z "$FRESH_EVENT_LOG_CORE_INSTALL" ]; then
     if ! (${SOLR_ROOT}/server/scripts/cloud-scripts/zkcli.sh -cmd upconfig -z localhost:2181 -confname ${EVENT_LOG_CORE_NAME} -confdir ${EVENT_LOG_CONFIGS_DIR}conf/ >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 		log "UPDATE of $EVENT_LOG_CORE_NAME config failed"
+	fi
+	if ! (curl "http://localhost:8983/solr/admin/cores?action=RELOAD&core=$EVENT_LOG_CORE_NAME" >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+		log "RELOAD of $EVENT_LOG_CORE_NAME failed"
 	fi
 else
 	if ! (${SOLR_ROOT}/bin/solr create -c ${EVENT_LOG_CORE_NAME} -d ${EVENT_LOG_CONFIGS_DIR} -rf 3 >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
