fixed subsitution into solr.in.sh values for server ports and zookeeper client port.

diff --git a/DEBIAN/postinst b/DEBIAN/postinst
--- a/DEBIAN/postinst
+++ b/DEBIAN/postinst
@@ -146,14 +146,14 @@ update-rc.d solr enable
 if ! (sed -i "s/$SERVER_1_TOKEN/$SERVER_1/g" ${SOLR_ROOT}/solr.in.sh >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
 	log "Unable to modify ${SOLR_ROOT}/solr.in.sh for $SERVER_1_TOKEN $SERVER_1"
 fi
-if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${JETTY_HOME}/start.ini >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-	log "Unable to modify ${JETTY_HOME}/start.ini for $SERVER_2_TOKEN $SERVER_2"
+if ! (sed -i "s/$SERVER_2_TOKEN/$SERVER_2/g" ${SOLR_ROOT}/solr.in.sh >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+	log "Unable to modify ${SOLR_ROOT}/solr.in.sh for $SERVER_2_TOKEN $SERVER_2"
 fi
-if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${JETTY_HOME}/start.ini >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-	log "Unable to modify ${JETTY_HOME}/start.ini for server $SERVER_3_TOKEN $SERVER_3"
+if ! (sed -i "s/$SERVER_3_TOKEN/$SERVER_3/g" ${SOLR_ROOT}/solr.in.sh >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+	log "Unable to modify ${SOLR_ROOT}/start.in.sh for server $SERVER_3_TOKEN $SERVER_3"
 fi
-if ! (sed -i "s/$ZK_CLIENT_PORT_TOKEN/$ZK_CLIENT_PORT/g" ${JETTY_HOME}/start.ini >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
-	log "Unable to modify ${JETTY_HOME}/start.ini for $ZK_CLIENT_PORT_TOKEN $ZK_CLIENT_PORT"
+if ! (sed -i "s/$ZK_CLIENT_PORT_TOKEN/$ZK_CLIENT_PORT/g" ${SOLR_ROOT}/start.ini >> ${D1_LOG_DIR}/${D1_LOG_FILE} 2>&1); then
+	log "Unable to modify ${SOLR_ROOT}/start.in.sh for $ZK_CLIENT_PORT_TOKEN $ZK_CLIENT_PORT"
 fi
 
 
